In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("top_restaurants_paris.csv")

In [4]:
df.head()

,name,address,rankingPosition,rating,description,numberOfReviews,priceLevel,priceRange
0,The Frog at Bercy Village,"25 Cour Saint Emilion, 75012 Paris France",19,4.5,THE FROG AT BERCY VILLAGE is situated in an hi...,2292,$$ - $$$,$11 - $17
1,Assanabel Saint-Germain,"38 rue Jacob, 75006 Paris France",15,4.5,"Assanabel Paris, les restaurants où notre spéc...",232,$$ - $$$,$20 - $90
2,114 Faubourg,"114 rue du Faubourg Saint Honore, 75008 Paris ...",35,4.5,La brasserie étoilée Récompensé par une étoile...,1953,$$$$,NaN
3,Nectar,"7 rue Mayran Hôtel Maison mère, 75009 Paris Fr...",5,5.0,Un refuge gastronomique effervescent et décomp...,243,$$ - $$$,$15 - $69
4,Nell'Arte,"58 rue Marguerite de Rochechouart, 75009 Paris...",14,5.0,NaN,350,$$ - $$$,$12 - $20

In [5]:
df.shape

(780, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             780 non-null    object
 1   address          780 non-null    object
 2   rankingPosition  780 non-null    int64
 3   rating           780 non-null    float64
 4   description      348 non-null    object
 5   numberOfReviews  780 non-null    int64
 6   priceLevel       780 non-null    object
 7   priceRange       551 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 48.9+ KB

In [7]:
df.dtypes

name                object
address             object
rankingPosition      int64
rating             float64
description         object
numberOfReviews      int64
priceLevel          object
priceRange          object
dtype: object

In [8]:
df.describe()            
df.describe(include='all')

,name,address,rankingPosition,rating,description,numberOfReviews,priceLevel,priceRange
count,780,780,780.000000,780.000000,348,780.000000,780,551
unique,774,775,NaN,NaN,346,NaN,3,354
top,Papelli,"4 avenue Carnot, 75017 Paris France",NaN,NaN,"Assanabel Paris, les restaurants où notre spéc...",NaN,$$ - $$$,$20 - $40
freq,2,2,NaN,NaN,2,NaN,570,14
mean,NaN,NaN,325.760256,4.582692,NaN,579.273077,NaN,NaN
std,NaN,NaN,228.765505,0.207115,NaN,475.020917,NaN,NaN
min,NaN,NaN,1.000000,4.000000,NaN,63.000000,NaN,NaN
25%,NaN,NaN,116.750000,4.500000,NaN,285.750000,NaN,NaN
50%,NaN,NaN,320.500000,4.500000,NaN,463.000000,NaN,NaN
75%,NaN,NaN,522.250000,4.500000,NaN,712.250000,NaN,NaN
max,NaN,NaN,773.000000,5.000000,NaN,4216.000000,NaN,NaN

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv("Housing.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Housing.csv'

In [11]:
df = pd.read_csv("top_restaurants_paris.csv")
df.head()

,name,address,rankingPosition,rating,description,numberOfReviews,priceLevel,priceRange
0,The Frog at Bercy Village,"25 Cour Saint Emilion, 75012 Paris France",19,4.5,THE FROG AT BERCY VILLAGE is situated in an hi...,2292,$$ - $$$,$11 - $17
1,Assanabel Saint-Germain,"38 rue Jacob, 75006 Paris France",15,4.5,"Assanabel Paris, les restaurants où notre spéc...",232,$$ - $$$,$20 - $90
2,114 Faubourg,"114 rue du Faubourg Saint Honore, 75008 Paris ...",35,4.5,La brasserie étoilée Récompensé par une étoile...,1953,$$$$,NaN
3,Nectar,"7 rue Mayran Hôtel Maison mère, 75009 Paris Fr...",5,5.0,Un refuge gastronomique effervescent et décomp...,243,$$ - $$$,$15 - $69
4,Nell'Arte,"58 rue Marguerite de Rochechouart, 75009 Paris...",14,5.0,NaN,350,$$ - $$$,$12 - $20

In [12]:
df.describe()

       rankingPosition      rating  numberOfReviews
count       780.000000  780.000000       780.000000
mean        325.760256    4.582692       579.273077
std         228.765505    0.207115       475.020917
min           1.000000    4.000000        63.000000
25%         116.750000    4.500000       285.750000
50%         320.500000    4.500000       463.000000
75%         522.250000    4.500000       712.250000
max         773.000000    5.000000      4216.000000

In [13]:
df['furnishingstatus'].value_counts()
df['mainroad'].value_counts()

KeyError: 'furnishingstatus'

In [14]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures, MinMaxScaler, OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.model_selection import train_test_split
import seaborn as sns

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [15]:
import streamlit as st
import pandas as pd

# قاعدة بيانات بسيطة
restaurants = pd.DataFrame({
    "Nom": ["Pizza House", "Sushi Time", "Tajine Marocain", "Burger King"],
    "Ville": ["Rabat", "Casablanca", "Rabat", "Marrakech"],
    "Prix": [80, 150, 60, 70],
    "Type": ["Pizza", "Sushi", "Marocain", "Burger"]
})

st.title("Recherche de Restaurants")

ville = st.text_input("دخل المدينة")

if ville:
    resultats = restaurants[
        restaurants["Ville"].str.lower() == ville.lower()
    ]

    if len(resultats) > 0:
        st.dataframe(resultats)
    else:
        st.write("ما لقيتش مطاعم فهاد المدينة")

2026-06-26 00:19:52.867 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-26 00:19:53.193
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Admin\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-06-26 00:19:53.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-26 00:19:53.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-26 00:19:53.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-26 00:19:53.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-26 00:19:53.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-26 00:19:53.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-26 00:19:53.209 Session state does not function when running a script without `streamlit run`
2026-06-26 00:19:53.213 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-26 00:19:53.219 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-26 00:19:53.221 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [16]:


# سؤال المستخدم
mot_cle = input("شنو بغيتي تاكل؟ (Pizza, Sushi, Burger...) : ")

# البحث
resultats = df[df["Type"].str.contains(mot_cle, case=False, na=False)]

if len(resultats) > 0:
    print("\nالنتائج:\n")
    print(resultats[["Nom", "Type", "Prix", "Adresse"]])
else:
    print("ما لقيت حتى نتيجة.")

شنو بغيتي تاكل؟ (Pizza, Sushi, Burger...) :  pizza

KeyError: 'Type'

In [17]:
print(df.columns)

Index(['name', 'address', 'rankingPosition', 'rating', 'description',
       'numberOfReviews', 'priceLevel', 'priceRange'],
      dtype='object')

In [18]:
print(df["description"].head(10))

0    THE FROG AT BERCY VILLAGE is situated in an hi...
1    Assanabel Paris, les restaurants où notre spéc...
2    La brasserie étoilée Récompensé par une étoile...
3    Un refuge gastronomique effervescent et décomp...
4                                                  NaN
5               Cuisine de marché et Vins de caractère
6    FROG XVI is situated in the 16th arrondissemen...
7                                                  NaN
8                                                  NaN
9    Smart pizza place in 5arrondisement. Here you ...
Name: description, dtype: object

In [19]:
mot_cle = input("شنو بغيتي تاكل؟ : ")

resultats = df[
    df["name"].str.contains(mot_cle, case=False, na=False) |
    df["description"].str.contains(mot_cle, case=False, na=False)
]

if not resultats.empty:
    print(resultats[["name", "rating", "priceRange", "address"]])
else:
    print("ما لقيت حتى مطعم")

شنو بغيتي تاكل؟ :  pizza

                                       name  rating priceRange  \
9                      Pizzeria Arrivederci     5.0   $9 - $22
20                              Da Giuseppe     5.0   $5 - $13
21                          Pizzamore Paris     5.0  $17 - $78
26                            Pizza Du Chef     4.5        NaN
36                                 Il Grano     4.5  $15 - $35
68                             Pizza Presto     5.0  $10 - $30
188           Respiro, Trattoria - Pizzeria     4.5   $7 - $43
202                                   Pop's     4.5  $12 - $25
292                                 Papelli     4.5   $9 - $18
304                         Pizza Caratello     4.5  $17 - $20
359                  La Villa Saint Baudile     4.5  $18 - $25
405                                 Papelli     4.5  $12 - $18
423                               L'Italien     4.5  $14 - $50
426             Gelateria Verdi Pizza Parma     4.5        NaN
489                      Il Forno Di Napoli     4.5        NaN
514                             Pizza Rossi     4.5   $8 - $18
545                               Pizzawawa     4.5  $21 - $41
555                              Chez Pippo     4.5  $10 - $32
569                                   Spiga     4.5   $6 - $22
577  Matteo Pizza Paris 9 Grands Boulevards     4.5  $15 - $35
620                              Vice Versa     4.5        NaN
755                                 Babalou     4.5  $14 - $22
774                            Pizza Di Gio     4.5        NaN
775                        Augusto Pizzeria     4.5  $15 - $35

                                               address
9                47 rue Gay Lussac, 75005 Paris France
20   76 rue du Faubourg Poissonniere, 75010 Paris F...
21             121 Avenue Du Maine, 75014 Paris France
26   11 rue Georges Marie, 92130 Issy-les-Moulineau...
36         212 B boulevard Pereire, 75017 Paris France
68   avenue Paul Vaillant Couturier, 93330 Neuilly-...
188           18 rue Maitre Albert, 75005 Paris France
202             38 rue du Ranelagh, 75016 Paris France
292  61 rue du Faubourg Saint Martin, 75010 Paris F...
304                   8 rue Audran, 75018 Paris France
359  23 rue Marx Dormoy En face de l'église Saint B...
405  74 rue du Faubourg Saint Denis, 75010 Paris Fr...
423             40 rue de Ponthieu, 75008 Paris France
426  1 rue du General Gallieni, 93110 Rosny-sous-Bo...
489  162 boulevard du Montparnasse Ouvert Le Dimanc...
514                 24 Rue Blondel, 75002 Paris France
545            35 rue Saint Honore, 75001 Paris France
555    31 avenue de la Bourdonnais, 75007 Paris France
569                   4 rue Parrot, 75012 Paris France
577  18 Rue Du Faubourg Montmartre, 75009 Paris France
620    71 rue des Voies du Bois, 92700 Colombes France
755                  4 rue Lamarck, 75018 Paris France
774         48 rue du Cherche Midi, 75006 Paris France
775            14 rue Victor Masse, 75009 Paris France